FROM debian:latest

RUN cd ~ && \
    apt-get update && \
    apt-get -y install git python3 python3-venv build-essential libssl-dev libffi-dev python-dev &&\ 
    git clone https://github.com/amirny2205/adv-backend-trainee-assignment && \
    cd adv-backend-trainee-assignment && \
    python3 -m venv env && \
    source ./env/bin/activate && \
    pip3 install -r requirements.txt && \
    python3 manage.py runserver 0
    

EXPOSE 4000
    