version: "3.8"

services:
  backend:
    build:
      dockerfile: Dockerfile_django
      args:
        REPO_DIR: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    working_dir: /root/adv-backend-trainee-assignment
    env_file: .env_docker_dev
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "asd;'kljasd;l"
      POSTGRES_DB: adv_backend_trainee_assignment




