FROM python:slim

WORKDIR /root/adv-backend-trainee-assignment


COPY ${REPO_DIR} /root/adv-backend-trainee-assignment/

RUN cd ~ && \
    apt-get update && \
    apt-get -y install git build-essential libssl-dev libffi-dev libpq-dev && \
    cd /root/adv-backend-trainee-assignment && \
    pip3 install -r requirements.txt




# ENTRYPOINT python3 manage.py runserver 0:8000


