# Generated by Django 4.1.2 on 2022-10-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_creation_date_alter_ad_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='main_photo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
