# Generated by Django 4.1.2 on 2022-10-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='main_photo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
