# Generated by Django 4.1.2 on 2022-10-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='test_boolean',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
