# Generated by Django 4.1.2 on 2022-10-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_test_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='test_boolean',
        ),
    ]
