# Generated by Django 4.1.2 on 2022-10-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_ad_test_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='main_photo',
        ),
    ]
