# Generated by Django 4.1.2 on 2022-10-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ad_main_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='main_photo',
        ),
    ]
