# Generated by Django 4.1.2 on 2022-10-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_remove_ad_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
